name: social_lite_technical_test
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  provider: ^6.1.4
  email_validator: ^3.0.0
  image_picker: ^1.1.2
  stomp_dart_client: ^2.1.3
  intl: ^0.18.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_screenutil: ^5.9.3
  get: ^4.7.2
  hive_generator: ^2.0.1
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/Lato/
    - assets/images/
    - assets/icons/
    - assets/logo/
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Black.ttf

